function [Swaprates, zerorate] = importfile_func()
%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\gebruiker\Desktop\VU\Master\IIALM\Case 1\Data case 1 final 2021 IIALM final.xlsx
%    Worksheet: Question 1
%
% Auto-generated by MATLAB on 22-Feb-2021 15:38:02

directory = "C:\Users\gebruiker\Desktop\VU\Master\IIALM\Case 1\Data case 1 final 2021 IIALM final.xlsx";
%% Setup the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 1);

% Specify sheet and range
opts.Sheet = "Question 1";
opts.DataRange = "B5:B24";

% Specify column names and types
opts.VariableNames = "Swaprates";
opts.VariableTypes = "double";

% Import the data
tbl = readtable(directory, opts, "UseExcel", false);

%% Convert to output type
Swaprates = tbl.Swaprates;

%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\gebruiker\Desktop\VU\Master\IIALM\Case 1\Data case 1 final 2021 IIALM final.xlsx
%    Worksheet: Question 1
%
% Auto-generated by MATLAB on 22-Feb-2021 15:46:48

%% Setup the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 1);

% Specify sheet and range
opts.Sheet = "Question 1";
opts.DataRange = "E5:E9";

% Specify column names and types
opts.VariableNames = "zerorate";
opts.VariableTypes = "double";

% Import the data
tbl = readtable(directory, opts, "UseExcel", false);

%% Convert to output type
zerorate = tbl.zerorate;

end